# Generated by Django 6.0.7 on 2026-08-02 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่ออุปกรณ์')),
                ('description', models.TextField(verbose_name='หน้าที่การทำงาน (เอาไว้ทำอะไร)')),
                ('how_to_use', models.TextField(verbose_name='วิธีการใช้งาน')),
                ('cleaning', models.TextField(verbose_name='วิธีการทำความสะอาด')),
                ('image', models.ImageField(upload_to='equipment/', verbose_name='รูปภาพอุปกรณ์')),
                ('video_id', models.CharField(help_text='ใส่เฉพาะ ID ของวิดีโอ YouTube เช่น ถ้าลิงก์คือ https://www.youtube.com/watch?v=dQw4w9WgXcQ ให้ใส่แค่ dQw4w9WgXcQ', max_length=50, verbose_name='YouTube Video ID')),
            ],
            options={
                'verbose_name': 'อุปกรณ์ทดลอง',
                'verbose_name_plural': 'อุปกรณ์ทดลองทั้งหมด',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='คะแนนที่ได้')),
                ('date_taken', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ทำแบบทดสอบ')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.equipment', verbose_name='อุปกรณ์ที่ทดสอบ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน')),
            ],
            options={
                'verbose_name': 'ผลคะแนนแบบทดสอบ',
                'verbose_name_plural': 'ผลคะแนนแบบทดสอบทั้งหมด',
            },
        ),
    ]
