# Generated by Django 6.0.7 on 2026-08-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='cleaning',
            field=models.TextField(blank=True, null=True, verbose_name='วิธีการเก็บรักษา'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='หน้าที่การทำงาน (เอาไว้ทำอะไร)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='how_to_use',
            field=models.TextField(blank=True, null=True, verbose_name='วิธีการใช้งาน'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='รูปภาพอุปกรณ์'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='video_id',
            field=models.CharField(blank=True, help_text='ใส่เฉพาะ ID ของวิดีโอ YouTube เช่น ถ้าลิงก์คือ https://www.youtube.com/watch?v=dQw4w9WgXcQ ให้ใส่แค่ dQw4w9WgXcQ', max_length=50, null=True, verbose_name='YouTube Video ID'),
        ),
    ]
