# Generated by Django 6.0.7 on 2026-08-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0002_alter_equipment_cleaning_alter_equipment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('glassware', 'เครื่องแก้ว (Glassware)'), ('instrument', 'เครื่องมือวิทยาศาสตร์ (Instruments)')], default='glassware', max_length=20, verbose_name='หมวดหมู่อุปกรณ์'),
        ),
    ]
