# Generated by Django 6.0.7 on 2026-08-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0003_equipment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='video_id',
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab_app.equipment', verbose_name='อุปกรณ์ที่ทดสอบ'),
        ),
    ]
