# Generated by Django 6.0.7 on 2026-08-02 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0004_remove_equipment_video_id_alter_quizresult_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz40Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='คะแนนที่ได้')),
                ('total_questions', models.IntegerField(default=40, verbose_name='จำนวนข้อทั้งหมด')),
                ('percentage', models.FloatField(default=0.0, verbose_name='คิดเป็นร้อยละ (%)')),
                ('passed', models.BooleanField(default=False, verbose_name='ผลการทดสอบ (ผ่าน 80%)')),
                ('user_answers', models.JSONField(default=dict, verbose_name='คำตอบของผู้ใช้')),
                ('date_taken', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ทำแบบทดสอบ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน')),
            ],
            options={
                'verbose_name': 'ผลสอบแบบทดสอบ 40 ข้อ',
                'verbose_name_plural': 'ผลสอบแบบทดสอบ 40 ข้อทั้งหมด',
            },
        ),
    ]
