# Generated by Django 6.0.7 on 2026-08-08 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0006_quizpretestresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizpretestresult',
            options={'verbose_name': 'ผลสอบแบบทดสอบก่อนเรียน', 'verbose_name_plural': 'ผลสอบแบบทดสอบก่อนเรียนทั้งหมด'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='อัปโหลดไฟล์วิดีโอ (MP4)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ลิงก์วิดีโอ (YouTube)'),
        ),
        migrations.AlterField(
            model_name='quizpretestresult',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่ทำแบบทดสอบ'),
        ),
        migrations.AlterField(
            model_name='quizpretestresult',
            name='percentage',
            field=models.FloatField(default=0.0, verbose_name='คิดเป็นร้อยละ (%)'),
        ),
        migrations.AlterField(
            model_name='quizpretestresult',
            name='score',
            field=models.IntegerField(verbose_name='คะแนนที่ได้'),
        ),
        migrations.AlterField(
            model_name='quizpretestresult',
            name='total_questions',
            field=models.IntegerField(default=40, verbose_name='จำนวนข้อทั้งหมด'),
        ),
        migrations.AlterField(
            model_name='quizpretestresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน'),
        ),
        migrations.AlterField(
            model_name='quizpretestresult',
            name='user_answers',
            field=models.JSONField(default=dict, verbose_name='คำตอบของผู้ใช้'),
        ),
    ]
