# Generated by Django 6.0.7 on 2026-09-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0007_alter_quizpretestresult_options_equipment_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='how_to_use',
        ),
    ]
