# Generated by Django 6.0.7 on 2026-09-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0008_remove_equipment_how_to_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='caution',
            field=models.TextField(blank=True, null=True, verbose_name='ข้อควรระวัง'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='how_to_use',
            field=models.TextField(blank=True, null=True, verbose_name='วิธีการใช้งาน'),
        ),
    ]
